In [1]:
from numpy import array
from keras.preprocessing.text import one_hot
from keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers import Embedding

In [2]:
corpus = [
    # Positive Reviews

    'This is an excellent movie',
    'The move was fantastic I like it',
    'You should watch it is brilliant',
    'Exceptionally good',
    'Wonderfully directed and executed I like it',
    'Its a fantastic series',
    'Never watched such a brillent movie',
    'It is a Wonderful movie',

    # Negtive Reviews

    "horrible acting",
    'waste of money',
    'pathetic picture',
    'It was very boring',
    'I did not like the movie',
    'The movie was horrible',
    'I will not recommend',
    'The acting is pathetic'
]

In [3]:
sentiments = array([1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0])

In [4]:
import nltk

nltk.download('punkt')

from nltk.tokenize import word_tokenize

all_words = []
for sent in corpus:
    tokenize_word = word_tokenize(sent)
    for word in tokenize_word:
        all_words.append(word)

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [5]:
unique_words = set(all_words)
print(len(unique_words))

45


In [6]:
embedded_sentences = [one_hot(sent, 50) for sent in corpus]
print(embedded_sentences )

[[5, 3, 26, 36, 9], [17, 5, 23, 20, 33, 6, 15], [16, 34, 6, 15, 3, 31], [35, 39], [22, 35, 18, 27, 33, 6, 15], [48, 3, 20, 5], [12, 37, 39, 3, 40, 9], [15, 3, 3, 30, 9], [16, 21], [8, 22, 24], [20, 28], [15, 23, 24, 15], [33, 46, 16, 6, 17, 9], [17, 9, 23, 16], [33, 3, 16, 24], [17, 21, 3, 20]]


In [7]:
word_count = lambda sentence: len(word_tokenize(sentence))
longest_sentence = max(corpus, key=word_count)
length_long_sentence = len(word_tokenize(longest_sentence))

In [8]:
padded_sentences = pad_sequences(embedded_sentences, length_long_sentence, padding='post')
print(padded_sentences)

[[ 5  3 26 36  9  0  0]
 [17  5 23 20 33  6 15]
 [16 34  6 15  3 31  0]
 [35 39  0  0  0  0  0]
 [22 35 18 27 33  6 15]
 [48  3 20  5  0  0  0]
 [12 37 39  3 40  9  0]
 [15  3  3 30  9  0  0]
 [16 21  0  0  0  0  0]
 [ 8 22 24  0  0  0  0]
 [20 28  0  0  0  0  0]
 [15 23 24 15  0  0  0]
 [33 46 16  6 17  9  0]
 [17  9 23 16  0  0  0]
 [33  3 16 24  0  0  0]
 [17 21  3 20  0  0  0]]


In [9]:
word_count = lambda sentence: len(word_tokenize(sentence))
longest_sentence = max(corpus, key=word_count)
length_long_sentence = len(word_tokenize(longest_sentence))

In [10]:
model = Sequential()
model.add(Embedding(50, 20, input_length=length_long_sentence))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))

In [11]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 7, 20)             1000      
                                                                 
 flatten (Flatten)           (None, 140)               0         
                                                                 
 dense (Dense)               (None, 1)                 141       
                                                                 
Total params: 1141 (4.46 KB)
Trainable params: 1141 (4.46 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [12]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['acc'])
print(model.summary())

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 7, 20)             1000      
                                                                 
 flatten (Flatten)           (None, 140)               0         
                                                                 
 dense (Dense)               (None, 1)                 141       
                                                                 
Total params: 1141 (4.46 KB)
Trainable params: 1141 (4.46 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
None


In [13]:
model.fit(padded_sentences, sentiments, epochs=100, verbose=1)

Epoch 1/100
1/1 [==============================] - 4s 4s/step - loss: 0.7048 - acc: 0.3125
Epoch 2/100
1/1 [==============================] - 0s 40ms/step - loss: 0.7012 - acc: 0.3125
Epoch 3/100
1/1 [==============================] - 0s 41ms/step - loss: 0.6976 - acc: 0.3750
Epoch 4/100
1/1 [==============================] - 0s 23ms/step - loss: 0.6941 - acc: 0.5000
Epoch 5/100
1/1 [==============================] - 0s 21ms/step - loss: 0.6905 - acc: 0.5625
Epoch 6/100
1/1 [==============================] - 0s 25ms/step - loss: 0.6870 - acc: 0.5000
Epoch 7/100
1/1 [==============================] - 0s 21ms/step - loss: 0.6835 - acc: 0.6250
Epoch 8/100
1/1 [==============================] - 0s 29ms/step - loss: 0.6800 - acc: 0.7500
Epoch 9/100
1/1 [==============================] - 0s 22ms/step - loss: 0.6765 - acc: 0.8125
Epoch 10/100
1/1 [==============================] - 0s 26ms/step - loss: 0.6730 - acc: 0.8125
Epoch 11/100
1/1 [==============================] - 0s 21ms/step - loss

In [14]:
loss, accuracy = model.evaluate(padded_sentences, sentiments, verbose=0)
print('Accuracy: %f' % (accuracy*100))

Accuracy: 93.750000
